"use strict";
const PRODUCTS = [{"id": 1, "name": "Nova X Smartphone", "price": 699.99, "category": "Smartphones", "description": "Fast 5G phone with OLED display and all-day battery.", "image": "../media/product-1.svg"}, {"id": 2, "name": "Orbit Pro Laptop", "price": 999.99, "category": "Laptops", "description": "Lightweight laptop for study, work and creative tasks.", "image": "../media/product-2.svg"}, {"id": 3, "name": "Pulse Wireless Earbuds", "price": 79.99, "category": "Audio", "description": "Compact earbuds with clear sound and charging case.", "image": "../media/product-3.svg"}, {"id": 4, "name": "Vision 4K Monitor", "price": 329.99, "category": "Displays", "description": "27-inch 4K monitor with vivid colours and slim bezels.", "image": "../media/product-4.svg"}, {"id": 5, "name": "Click Mechanical Keyboard", "price": 89.99, "category": "Accessories", "description": "Responsive keyboard with comfortable tactile switches.", "image": "../media/product-5.svg"}, {"id": 6, "name": "Glide Wireless Mouse", "price": 39.99, "category": "Accessories", "description": "Ergonomic wireless mouse with adjustable sensitivity.", "image": "../media/product-6.svg"}, {"id": 7, "name": "Echo Bluetooth Speaker", "price": 59.99, "category": "Audio", "description": "Portable speaker with rich sound and splash resistance.", "image": "../media/product-7.svg"}, {"id": 8, "name": "ChargeMax Power Bank", "price": 44.99, "category": "Power", "description": "20,000mAh portable charger with fast USB-C output.", "image": "../media/product-8.svg"}, {"id": 9, "name": "Frame Smartwatch", "price": 149.99, "category": "Wearables", "description": "Fitness tracking, notifications and heart-rate monitoring.", "image": "../media/product-9.svg"}, {"id": 10, "name": "Snap HD Webcam", "price": 54.99, "category": "Cameras", "description": "1080p webcam with privacy cover and built-in microphone.", "image": "../media/product-10.svg"}, {"id": 11, "name": "Link USB-C Hub", "price": 49.99, "category": "Accessories", "description": "Seven-port hub for HDMI, USB, memory cards and charging.", "image": "../media/product-11.svg"}, {"id": 12, "name": "Guard Laptop Sleeve", "price": 24.99, "category": "Accessories", "description": "Padded water-resistant sleeve for 13- and 14-inch laptops.", "image": "../media/product-12.svg"}];
const CART_KEY = "technest-cart";
function getCart(){try{return JSON.parse(localStorage.getItem(CART_KEY))||[];}catch{return [];}}
function saveCart(cart){localStorage.setItem(CART_KEY,JSON.stringify(cart));updateCartCount();}
function money(value){return new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(value);}
function updateCartCount(){const count=getCart().reduce((sum,item)=>sum+item.quantity,0);document.querySelectorAll("#cart-count").forEach(el=>el.textContent=count);}
function showToast(message){const toast=document.getElementById("toast");if(!toast)return;toast.textContent=message;toast.classList.add("show");window.clearTimeout(showToast.timer);showToast.timer=window.setTimeout(()=>toast.classList.remove("show"),2200);}
function addToCart(id){const cart=getCart();const found=cart.find(item=>item.id===id);if(found)found.quantity+=1;else cart.push({id,quantity:1});saveCart(cart);const product=PRODUCTS.find(p=>p.id===id);showToast(`${product.name} added to cart`);}
function openProductDetails(id){const dialog=document.getElementById("product-dialog");const content=document.getElementById("dialog-content");const product=PRODUCTS.find(p=>p.id===id);if(!dialog||!content||!product)return;content.innerHTML=`<div class="dialog-product"><img src="${product.image}" alt="${product.name}"><div><p class="category">${product.category}</p><h2 id="dialog-title">${product.name}</h2><p>${product.description}</p><p class="price">${money(product.price)}</p><button class="button dialog-add" data-id="${product.id}">Add to cart</button></div></div>`;dialog.showModal();content.querySelector(".dialog-add").addEventListener("click",()=>addToCart(id));}
function setupGlobal(){document.getElementById("year").textContent=new Date().getFullYear();updateCartCount();const menu=document.querySelector(".menu-button");const nav=document.getElementById("primary-nav");if(menu&&nav)menu.addEventListener("click",()=>{const open=nav.classList.toggle("open");menu.setAttribute("aria-expanded",String(open));});document.addEventListener("click",event=>{const add=event.target.closest(".add-to-cart");if(add)addToCart(Number(add.dataset.id));const details=event.target.closest(".view-details");if(details)openProductDetails(Number(details.dataset.id));const close=event.target.closest(".dialog-close");if(close)close.closest("dialog").close();});document.querySelectorAll("dialog").forEach(dialog=>dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.close();}));const views=Number(localStorage.getItem("technest-page-views")||0)+1;localStorage.setItem("technest-page-views",String(views));}
function setupFilters(){const search=document.getElementById("product-search");const category=document.getElementById("category-filter");const cards=[...document.querySelectorAll(".product-card")];if(!search||!category)return;const filter=()=>{const term=search.value.trim().toLowerCase();const selected=category.value.toLowerCase();let shown=0;cards.forEach(card=>{const matchText=card.dataset.name.includes(term);const matchCat=selected==="all"||card.dataset.category===selected;card.hidden=!(matchText&&matchCat);if(!card.hidden)shown++;});document.getElementById("results-count").textContent=`${shown} product${shown===1?"":"s"} shown`;document.getElementById("no-results").hidden=shown!==0;};search.addEventListener("input",filter);category.addEventListener("change",filter);}
function renderCart(){const container=document.getElementById("cart-items");if(!container)return;const cart=getCart();if(cart.length===0){container.innerHTML='<div class="empty-state"><h2>Your cart is empty</h2><p>Add products to begin your order.</p></div>';updateTotals(0);return;}container.innerHTML=cart.map(item=>{const p=PRODUCTS.find(x=>x.id===item.id);return `<article class="cart-item"><img src="${p.image}" alt="${p.name}"><div><p class="category">${p.category}</p><h2>${p.name}</h2><p>${money(p.price)} each</p><div class="quantity-controls" aria-label="Quantity controls for ${p.name}"><button class="qty" data-action="decrease" data-id="${p.id}" aria-label="Decrease quantity">−</button><strong>${item.quantity}</strong><button class="qty" data-action="increase" data-id="${p.id}" aria-label="Increase quantity">+</button><button class="remove-button" data-id="${p.id}">Remove</button></div></div><strong>${money(p.price*item.quantity)}</strong></article>`;}).join("");const subtotal=cart.reduce((sum,item)=>{const p=PRODUCTS.find(x=>x.id===item.id);return sum+p.price*item.quantity;},0);updateTotals(subtotal);}
function updateTotals(subtotal){const delivery=subtotal>0&&subtotal<100?4.99:0;document.getElementById("subtotal").textContent=money(subtotal);document.getElementById("delivery").textContent=money(delivery);document.getElementById("cart-total").textContent=money(subtotal+delivery);const checkout=document.getElementById("checkout-button");if(checkout)checkout.disabled=subtotal===0;}
function setupCart(){const container=document.getElementById("cart-items");if(!container)return;renderCart();container.addEventListener("click",e=>{const qty=e.target.closest(".qty");const remove=e.target.closest(".remove-button");let cart=getCart();if(qty){const item=cart.find(x=>x.id===Number(qty.dataset.id));if(item)qty.dataset.action==="increase"?item.quantity++:item.quantity--;cart=cart.filter(x=>x.quantity>0);saveCart(cart);renderCart();}if(remove){cart=cart.filter(x=>x.id!==Number(remove.dataset.id));saveCart(cart);renderCart();showToast("Item removed");}});const checkout=document.getElementById("checkout-button");const dialog=document.getElementById("checkout-dialog");if(checkout&&dialog)checkout.addEventListener("click",()=>dialog.showModal());setupForm("checkout-form",{name:"Please enter at least 2 characters.",email:"Enter a valid email address.",address:"Enter at least 10 characters."},()=>{localStorage.removeItem(CART_KEY);renderCart();updateCartCount();dialog.close();showToast("Demonstration order placed");});}
function setupForm(formId,messages,onSuccess){const form=document.getElementById(formId);if(!form)return;form.addEventListener("submit",e=>{e.preventDefault();let valid=true;[...form.elements].forEach(field=>{if(!field.name)return;const error=document.getElementById(`${field.id}-error`);if(!field.checkValidity()){valid=false;field.setAttribute("aria-invalid","true");if(error)error.textContent=messages[field.name]||"Please complete this field.";}else{field.removeAttribute("aria-invalid");if(error)error.textContent="";}});if(valid){onSuccess();form.reset();}});}
function setupContact(){setupForm("contact-form",{name:"Please enter at least 2 characters.",email:"Enter a valid email address.",subject:"Choose a subject.",message:"Enter at least 10 characters."},()=>{document.getElementById("contact-success").textContent="Thank you. Your demonstration message has been validated successfully.";});}
document.addEventListener("DOMContentLoaded",()=>{setupGlobal();setupFilters();setupCart();setupContact();});
